#!/bin/bash
#SBATCH --partition=a40
#SBATCH --gres=gpu:1
#SBATCH --mem=30G
#SBATCH --cpus-per-task=4
#SBATCH --time=1:00:00
#SBATCH --output=train_%j.out

echo "Job ID: $SLURM_JOB_ID"
echo "Running on node: $(hostname)"
echo "Allocated CPUs: $SLURM_CPUS_ON_NODE"
echo "Allocated Memory: $SLURM_MEM_PER_NODE"
echo "Allocated GPU(s):"
nvidia-smi
echo "Free RAM:"
free -h
echo "Disk space in /tmp:"
df -h /tmp
echo "-------------------------"
export PYTHONUNBUFFERED=1

# activate virtual environment
source /vol/bitbucket/mdp25/lerobot310/bin/activate

huggingface-cli login --token ${my_hugging_face_token}

lerobot-train \
  --dataset.repo_id=mattpidden/so101-dataset-act \
  --policy.type=act \
  --output_dir=$WORKDIR/output \
  --job_name=act_run \
  --policy.device=cuda \
  --policy.repo_id=mattpidden/so101_act_policy
