#!/bin/bash
#SBATCH --partition=a100
#SBATCH --gres=gpu:1
#SBATCH --mem=64G
#SBATCH --cpus-per-task=4
#SBATCH --time=12:00:00
#SBATCH --output=pi05_10k_train_%j.out

echo "Job ID: $SLURM_JOB_ID"
echo "Running on node: $(hostname)"
echo "Allocated CPUs: $SLURM_CPUS_ON_NODE"
echo "Allocated Memory: $SLURM_MEM_PER_NODE"
echo "Allocated GPU(s):"
nvidia-smi
echo "Free RAM:"
free -h
echo "Disk space in /tmp:"
df -h /tmp
echo "-------------------------"
export PYTHONUNBUFFERED=1
export CUDA_VISIBLE_DEVICES=0

# Activate virtual environment
export PATH="/vol/dissolve/justin/miniforge3/bin:$PATH"
source /vol/dissolve/justin/miniforge3/etc/profile.d/conda.sh
conda activate lerobot

# Temporary cache folder on the compute node's local SSD
mkdir -p /tmp/jzt25_hf_cache

# Routing Hugging Face to use fast local drive instead of the network drive
export HF_HOME=/tmp/jzt25_hf_cache
export TRANSFORMERS_CACHE=/tmp/jzt25_hf_cache
export HF_DATASETS_CACHE=/tmp/jzt25_hf_cache

export HF_TOKEN=$"HF_TOKEN"

lerobot-train \
  --dataset.repo_id=justintiensmith/multicolour_block_pick_place_2 \
  --policy.type=pi05 \
  --output_dir=/vol/dissolve/justin/outputs/pi05_10k_multicolour_block_pick_place_2 \
  --job_name=pi05_training \
  --policy.pretrained_path=lerobot/pi05_base \
  --policy.dtype=bfloat16 \
  --policy.gradient_checkpointing=true \
  --policy.freeze_vision_encoder=false \
  --policy.train_expert_only=false \
  --steps=10000 \
  --batch_size=32 \
  --save_freq 1000 \
  --policy.device=cuda \
  --policy.repo_id=justintiensmith/pi05_10k_multicolour_block_pick_place_2 \
  --policy.compile_model=false \
  --policy.normalization_mapping='{"ACTION": "MEAN_STD", "STATE": "MEAN_STD", "VISUAL": "IDENTITY"}'
