#!/bin/bash
#SBATCH --job-name=xvla_train
#SBATCH --partition=a100
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --cpus-per-task=8
#SBATCH --time=12:00:00
#SBATCH --output=xvla_train_%j.out

set -euo pipefail

echo "Job ID: $SLURM_JOB_ID"
echo "Running on node: $(hostname)"
echo "Allocated CPUs: $SLURM_CPUS_ON_NODE"
echo "Allocated Memory: $SLURM_MEM_PER_NODE"
echo "Allocated GPU(s):"
nvidia-smi
echo "Free RAM:"
free -h
echo "Disk space in /tmp:"
df -h /tmp
echo "-------------------------"

export PYTHONUNBUFFERED=1

# Activate virtual environment
source /vol/bitbucket/jzt25/lerobot312/bin/activate

hf auth login --token "$HF_TOKEN"

lerobot-train \
  --dataset.repo_id=mattpidden/smol-vla-test-dataset \
  --policy.resize_imgs_with_padding='[224, 224]' \
  --output_dir=./outputs/xvla_training \
  --job_name=xvla_training \
  --policy.path="lerobot/xvla-base" \
  --policy.repo_id="HF_USER/xvla-your-robot" \
  --policy.dtype=bfloat16 \
  --policy.action_mode=auto \
  --steps=20000 \
  --policy.device=cuda \
  --policy.freeze_vision_encoder=false \
  --policy.freeze_language_encoder=false \
  --policy.train_policy_transformer=true \
  --policy.train_soft_prompts=true \
  --rename_map='{"observation.images.claw": "observation.images.image", "observation.images.world": "observation.images.image2"}' \
  --policy.empty_cameras=1
