#!/bin/bash
#SBATCH --partition=a100
#SBATCH --gres=gpu:1
#SBATCH --mem=64G
#SBATCH --cpus-per-task=4
#SBATCH --time=16:00:00
#SBATCH --output=xvla_train_%j.out

echo "Job ID: $SLURM_JOB_ID"
echo "Running on node: $(hostname)"
echo "Allocated CPUs: $SLURM_CPUS_ON_NODE"
echo "Allocated Memory: $SLURM_MEM_PER_NODE"
echo "Allocated GPU(s):"
nvidia-smi
echo "Free RAM:"
free -h
echo "Disk space in /tmp:"
df -h /tmp
echo "-------------------------"
export PYTHONUNBUFFERED=1
export CUDA_VISIBLE_DEVICES=0

# Activate virtual environment
export PATH="/vol/dissolve/justin/miniforge3/bin:$PATH"
source /vol/dissolve/justin/miniforge3/etc/profile.d/conda.sh
conda activate lerobot_xvla

# Temporary cache folder on the compute node's local SSD
mkdir -p /tmp/jzt25_hf_cache

# Routing Hugging Face to use fast local drive instead of the network drive
export HF_HOME=/tmp/jzt25_hf_cache
export TRANSFORMERS_CACHE=/tmp/jzt25_hf_cache
export HF_DATASETS_CACHE=/tmp/jzt25_hf_cache

hf auth login
#export HF_TOKEN=$"HF_TOKEN"

lerobot-train \
  --dataset.repo_id=justintiensmith/red_block_precision-multicolour_block_pick_place \
  --output_dir=/vol/dissolve/justin/outputs/xvla_25k \
  --job_name=xvla \
  --policy.path="lerobot/xvla-base" \
  --policy.repo_id="justintiensmith/red_block_precision-multicolour_block_pick_place" \
  --policy.dtype=bfloat16 \
  --policy.action_mode=auto \
  --policy.device=cuda \
  --steps=25000 \
  --batch_size=32 \
  --num_workers=8 \
  --save_freq 1000 \
  --log_freq=50 \
  --policy.freeze_vision_encoder=false \
  --policy.freeze_language_encoder=false \
  --policy.train_policy_transformer=true \
  --policy.train_soft_prompts=true \
  --policy.empty_cameras=1 \
  --rename_map='{"observation.images.wrist": "observation.images.image", "observation.images.world": "observation.images.image2"}' \
  --policy.push_to_hub=true
